version: '3.8'

services:
  web:
    build: 
      context: ./restapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio
      - database
    environment:
      - DB_HOST=database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: temperatures_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789

  redis:
    image: redis:latest

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  minio_data:
