version: '3.8'

services:
  web:
    build: ./restapi_app  
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DB_HOST=database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: temperatures_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789

  redis:
    image: redis:latest
