# Generated by Django 5.0.3 on 2024-04-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_id', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(unique=True)),
            ],
            options={
                'db_table': 'temperature',
            },
        ),
    ]
